// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDGy5aupTTM0YKXWhW74Y0tJCSLCFeLGI',
    appId: '1:113885842378:web:f50eda14575313104d5d33',
    messagingSenderId: '113885842378',
    projectId: 'registration-ee089',
    authDomain: 'registration-ee089.firebaseapp.com',
    storageBucket: 'registration-ee089.firebasestorage.app',
    measurementId: 'G-M2FS37862W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWarRtDXKTyZtgLLBcrv599J1dVqlv6A',
    appId: '1:113885842378:android:ec0340a7e2b272a04d5d33',
    messagingSenderId: '113885842378',
    projectId: 'registration-ee089',
    storageBucket: 'registration-ee089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-DSVqs2thSrQ4o5BrquQo1RFVc7-Cqy0',
    appId: '1:113885842378:ios:bee325ed6cf9f17e4d5d33',
    messagingSenderId: '113885842378',
    projectId: 'registration-ee089',
    storageBucket: 'registration-ee089.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-DSVqs2thSrQ4o5BrquQo1RFVc7-Cqy0',
    appId: '1:113885842378:ios:bee325ed6cf9f17e4d5d33',
    messagingSenderId: '113885842378',
    projectId: 'registration-ee089',
    storageBucket: 'registration-ee089.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDGy5aupTTM0YKXWhW74Y0tJCSLCFeLGI',
    appId: '1:113885842378:web:6cd7f800e075116c4d5d33',
    messagingSenderId: '113885842378',
    projectId: 'registration-ee089',
    authDomain: 'registration-ee089.firebaseapp.com',
    storageBucket: 'registration-ee089.firebasestorage.app',
    measurementId: 'G-83BR1Y0GKS',
  );
}
